trigger:
- master
- master-next
- dunfell

schedules:
- cron: "0 12 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

variables:
    DISTRO: 'freertos'
    SSTATE_MIRRORS: 'file://.* http://sstate.yoctoproject.org/dev/PATH;downloadfilename=PATH;'
    MACHINE: 'qemuarmv5'
    DEPLOY_ARTIFACTS_DIR: '/mnt/deploydir/'
    DL_DIR: '/home/vsts/downloads/'
    SSTATE_DIR: '/home/vsts/sstate-cache/'

jobs:
  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'freertos'
      machine: 'qemuarmv5'

  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'qemuarmv5'
